/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class GetCalculateForXfersInputBuilder {
    //the instance to build
    private GetCalculateForXfersInput getCalculateForXfersInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCalculateForXfersInputBuilder() {
        getCalculateForXfersInput = new GetCalculateForXfersInput();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCalculateForXfersInputBuilder operation(OperationTypeEnum operation) {
        getCalculateForXfersInput.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCalculateForXfersInputBuilder x(double x) {
        getCalculateForXfersInput.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCalculateForXfersInputBuilder y(double y) {
        getCalculateForXfersInput.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCalculateForXfersInput build() {
        return getCalculateForXfersInput;
    }
}